import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="md:grid md:grid-cols-6">
          <div className="drawer drawer-mobile col-span-1">
            <input id="my-drawer-2" type="checkbox" className="drawer-toggle" />
            <div className="drawer-content flex flex-col items-center justify-center">
              <label
                htmlFor="my-drawer-2"
                className="btn btn-primary drawer-button lg:hidden"
              >
                Open drawer
              </label>
            </div>
            <div className="drawer-side">
              <label htmlFor="my-drawer-2" className="drawer-overlay"></label>
              <ul className="menu p-4 w-80 bg-neutral-900 text-base-content">
                <li>
                  <Link href={"/students"}>Students</Link>
                </li>
                <li>
                  <Link href={"/domains"}>Project Domains</Link>
                </li>
              </ul>
            </div>
          </div>
          <div className="col-span-4 px-5 py-5"> {children}</div>
        </div>
      </body>
    </html>
  );
}
